import React from 'react';
import { Sparkles, BookOpen, Target, CheckCircle2, ArrowRight, AlertTriangle, ShieldCheck } from 'lucide-react';
import { StudyRecommendation } from '../lib/api';

interface StudyCoachTabProps {
  recommendation: StudyRecommendation | null;
  onStartPractice: (topic: string) => void;
}

export const StudyCoachTab: React.FC<StudyCoachTabProps> = ({
  recommendation,
  onStartPractice,
}) => {
  if (!recommendation) {
    return (
      <div className="p-8 text-center bg-white rounded-2xl border border-slate-200">
        <p className="text-sm text-slate-500">Generating personalized AI Study Coach recommendations...</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Hero Header */}
      <div className="bg-gradient-to-r from-sky-900 via-indigo-900 to-slate-950 text-white p-6 sm:p-8 rounded-2xl shadow-md">
        <div className="max-w-2xl">
          <span className="text-xs font-bold uppercase tracking-wider text-sky-300 bg-sky-500/20 px-3 py-1 rounded-full border border-sky-400/30">
            Differentiated Feature • Phase 4
          </span>
          <h1 className="text-2xl sm:text-3xl font-bold mt-3 flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-amber-400" />
            AI Study Coach
          </h1>
          <p className="text-sm text-slate-300 mt-2 leading-relaxed">
            Your personalized study roadmap is generated by deterministically analyzing your actual course progress,
            question-level accuracy, and error frequencies. The AI Study Coach never fabricates reasons.
          </p>
        </div>
      </div>

      {/* Primary Recommendation Card */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 sm:p-8 shadow-sm space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-100">
          <div>
            <span className="text-xs font-bold uppercase tracking-wide text-red-600 bg-red-50 px-2.5 py-1 rounded-md border border-red-200">
              Immediate Priority
            </span>
            <h2 className="text-2xl font-black text-slate-900 mt-2">
              {recommendation.priority_topic}
            </h2>
            {recommendation.skill && (
              <p className="text-xs text-slate-500 mt-0.5">Subject Domain: {recommendation.skill}</p>
            )}
          </div>

          {recommendation.accuracy_percentage !== undefined && (
            <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-center sm:text-right">
              <span className="text-xs font-semibold text-red-800">Recorded Accuracy</span>
              <p className="text-3xl font-extrabold text-red-700">
                {recommendation.accuracy_percentage}%
              </p>
              <span className="text-[11px] text-red-600 font-medium">
                {recommendation.failed_count} failed of {recommendation.total_questions} questions
              </span>
            </div>
          )}
        </div>

        {/* Factual Rationale */}
        <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
          <span className="text-xs font-bold uppercase tracking-wider text-slate-500">
            Factual Assessment Rationale:
          </span>
          <p className="text-sm text-slate-800 font-medium leading-relaxed">
            {recommendation.reason}
          </p>
        </div>

        {/* Action Plan Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-5 rounded-xl border border-sky-100 bg-sky-50/40 space-y-2">
            <div className="flex items-center gap-2 text-sky-800 font-bold text-sm">
              <BookOpen className="h-4 w-4 text-sky-600" />
              <span>1. Recommended Course Material</span>
            </div>
            <p className="text-xs text-slate-700 leading-relaxed font-mono bg-white p-2.5 rounded-lg border border-sky-200">
              {recommendation.relevant_course_material}
            </p>
            <p className="text-xs text-slate-600 leading-relaxed pt-1">
              {recommendation.recommended_action}
            </p>
          </div>

          <div className="p-5 rounded-xl border border-emerald-100 bg-emerald-50/40 space-y-2 flex flex-col justify-between">
            <div>
              <div className="flex items-center gap-2 text-emerald-800 font-bold text-sm">
                <Target className="h-4 w-4 text-emerald-600" />
                <span>2. Targeted Practice Goal</span>
              </div>
              <p className="text-xs text-slate-700 leading-relaxed font-medium mt-2">
                {recommendation.practice_recommendation}
              </p>
            </div>

            <button
              onClick={() => onStartPractice(recommendation.priority_topic)}
              className="mt-4 w-full bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold py-2.5 px-4 rounded-lg shadow-sm transition flex items-center justify-center gap-2"
            >
              Start Practice on {recommendation.priority_topic} <ArrowRight className="h-3.5 w-3.5" />
            </button>
          </div>
        </div>

        {/* Guardrail Guarantee Banner */}
        <div className="pt-4 border-t border-slate-100 flex items-center gap-2 text-xs text-slate-400">
          <ShieldCheck className="h-4 w-4 text-emerald-600" />
          <span>
            Hallucination Guardrail Active: Recommendations are strictly synthesized from real student quiz attempts and accredited syllabus files.
          </span>
        </div>
      </div>
    </div>
  );
};
